= dotvim

My vim configuration

== Install

. Clone this to ++~/.vim++
** Linux
+
[source,sh]
----
git clone <repo_url> ~/.vim
cd ~/.vim
git submodule update --init
----

** Windows
+
Using TortoiseGit's ++Git clone...++ menu, check ++Recursive++。
+
NOTE: You should clone to ~/vimfiles instead of ~/.vim in Windows.

. Make ++\~/.vimrc++ call ++~/.vim/vimrc++
+
[source,sh]
----
echo 'source $HOME/.vim/vimrc' > ~/.vimrc
----

. Execute vim, and install plugins:
+
----
:NeoBundleInstall
----

. Make vimproc dll or so
+
** For Linux, executes ++~/.vim/setup.sh++ to make ++vimproc_**.so++
** For Windows, download and extract ++vimproc_win**.dll++ to
++~/.vim/bundle/vimproc/autoload/++ 
+
----
https://github.com/Shougo/vimproc/downloads
----

. All done, you are ready to use.

== Upgrading

. Use git pull to update to the lastest version.

. Start vim, clean up unused plugins:
+
----
:NeoBundleClean
----

. Upgrade existing plugins and install new plugins:
+
----
:NeoBundleUpdate
----

. run ++~/.vim/setup.sh++ to recompile vimproc if necessary.

== Using 443 port to access github via ssh

If you can't access github via standard port 22, you can add these
lines to ++~/.ssh/config++ to access github through https port:

--------------------
Host github.com
  Hostname ssh.github.com
  User git
  Port 443
--------------------

